# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/BRAM2/BRAM2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM2 || ORIG_REF_NAME==BRAM2} -quiet] -quiet

# IP: ip/BRAM1/BRAM1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM1 || ORIG_REF_NAME==BRAM1} -quiet] -quiet

# XDC: /home/ahmetenesturan/Projects/SSTU/SSTU_deney8/SSTU_deney8.gen/sources_1/ip/BRAM2/BRAM2_ooc.xdc

# XDC: /home/ahmetenesturan/Projects/SSTU/SSTU_deney8/SSTU_deney8.gen/sources_1/ip/BRAM1/BRAM1_ooc.xdc
